<?php /** @var \PixelOpen\CloudflareTurnstile\Block\Turnstile $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<div id="<?= $escaper->escapeHtmlAttr($block->getId()) ?>" class="cloudflare-turnstile" data-bind="scope:'cloudflare-turnstile-<?= $escaper->escapeHtmlAttr($block->getId()) ?>'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
{
    "#<?= $escaper->escapeJs($block->getId()) ?>": {
        "Magento_Ui/js/core/app": {
            "components": {
                "cloudflare-turnstile-<?= $escaper->escapeJs($block->getId()) ?>": {
                    "component": "PixelOpen_CloudflareTurnstile/js/view/turnstile",
                    "action": "<?= $escaper->escapeJs($block->getAction()) ?>",
                    "size": "<?= $escaper->escapeJs($block->getSize()) ?>",
                    "theme": "<?= $escaper->escapeJs($block->getTheme()) ?>",
                    "configSource": "turnstileConfig"
                }
            }
        }
    }
}
</script>
